# Generated by Django 5.0.1 on 2024-01-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created'], 'verbose_name': 'proyecto', 'verbose_name_plural': 'proyectos'},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='updates',
            new_name='updated',
        ),
        migrations.AlterField(
            model_name='project',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='projects'),
        ),
    ]
